transcrobes:
  bingSubscriptionKey: yourAPIToken
  hosts: ['transcrobes.example.com']
  #ingress:
  #  tls:
  #    issuer: letsencrypt-prod

certissuer:
  prod:
    email: anton@melser.org  # You MUST declare a valid email here, even for staging!
  staging:
    enabled: true
    email: yourname@example.com  # You MUST declare a valid email here, even for staging!

#ingress:
#  controller:
#    service:
#      nodePorts:
#        https: yourPortNumber
