apiVersion: v2
name: transcrobes
description: A Kubernetes Helm Chart for installing Transcrobes
version: 0.0.16
keywords:
  - Transcrobes
  - transcrob.es
sources:
  - https://gitlab.com/transcrobes/charts
home: https://transcrob.es
icon: https://transcrob.es/img/tc128.png
dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - transcrobes-database

  - name: ingress-nginx
    version: 3.x.x
    alias: ingress  # because https://github.com/helm/helm/issues/2192
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled  # FIXME: this doesn't appear to work
    tags:
      - transcrobes-nginx

  - name: kafka
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
    tags:
      - transcrobes-kafka
