{{- if and .Values.ankrobes.enabled .Values.serviceAccounts.ankrobes.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "transcrobes.ankrobes.labels" . | nindent 4 }}
  name: {{ template "transcrobes.serviceAccountName.ankrobes" . }}
{{- end -}}
