{{- if and .Values.ankrobes.enabled .Values.ankrobes.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transcrobes.ankrobes.fullname" . }}
  labels:
    {{- include "transcrobes.ankrobes.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.ankrobes.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ankrobes.persistence.size }}
status: {}
{{- end }}
