{{- if .Values.importsrunner.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transcrobes.transcrobes.fullname" . }}-importsrunner
  labels:
    {{- include "transcrobes.importsrunner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.importsrunner.replicaCount }}
  {{- if .Values.importsrunner.strategy }}
  strategy:
{{ toYaml .Values.importsrunner.strategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transcrobes.importsrunner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.importsrunner.podAnnotations }}
      annotations:
{{ toYaml .Values.importsrunner.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "transcrobes.importsrunner.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:13
          command: ['sh', '-c',
            'until psql -c "select 1;";
            do echo waiting for database; sleep 2; done;']
          env:
            - name: PGUSER
              value: "{{ .Values.pgha.postgresql.username }}"
            - name: PGDATABASE
              value: "{{ .Values.pgha.postgresql.database }}"
            - name: PGPASSWORD
              value: "{{ .Values.pgha.postgresql.password }}"
            - name: PGHOST
              value: "{{ .Release.Name }}-pgha-pgpool"

      containers:
        - name: {{ template "transcrobes.name" . }}-{{ .Values.importsrunner.name }}
          image: "{{ .Values.transcrobes.image.repository }}:{{ .Values.transcrobes.image.tag }}"
          imagePullPolicy: {{ .Values.transcrobes.image.pullPolicy }}
          command: ["/bin/bash", "/app/scripts/runmanage.sh"]
          args: ["imports_processor"]
          env:
            {{- range $key, $value := .Values.importsrunner.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.importsrunner.debug }}
            - name: TRANSCROBES_DEBUG
              value: "True"
            {{- end }}
            - name: PYTHONUNBUFFERED  # MUST put or no logs printed to kube, but probably should be in values
              value: "0"
            - name: TC_POSTGRES_USER
              value: "{{ .Values.pgha.postgresql.username }}"
            - name: TC_POSTGRES_DATABASE
              value: "{{ .Values.pgha.postgresql.database }}"
            - name: TC_POSTGRES_PASSWORD
              value: "{{ .Values.pgha.postgresql.password }}"
            - name: TC_POSTGRES_HOST
              value: "{{ .Release.Name }}-pgha-pgpool"
            - name: TRANSCROBES_MEDIA_ROOT
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.persistence.mediaPath }}"
            - name: TRANSCROBES_SECRET_KEY
              value: "{{ .Values.transcrobes.secretKey }}"
            - name: TRANSCROBES_IMPORT_PARSE_CHUNK_SIZE_BYTES
              value: "{{ .Values.importsrunner.application.importParseChunkSizeBytes }}"
            - name: TRANSCROBES_IMPORT_DETECT_CHUNK_SIZE_BYTES
              value: "{{ .Values.importsrunner.application.importDetectChunkSizeBytes }}"

            - name: TRANSCROBES_ZH_CORENLP_HOST
              value: {{ include "transcrobes.corenlpZh.fullname" . }}
            {{- if .Values.importsrunner.debug }}
            - name: TRANSCROBES_DEBUG
              value: "True"
            {{- end }}
            - name: TRANSCROBES_BING_SUBSCRIPTION_KEY
              value: "{{ .Values.transcrobes.bingSubscriptionKey }}"
            - name: TRANSCROBES_BING_API_HOST
              value: "{{ .Values.transcrobes.bingApiHost }}"
            - name: TRANSCROBES_ZH_EN_CEDICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhEnCedict.path }}"
            - name: TRANSCROBES_ZH_EN_CEDICT_INMEM
              value: "{{ .Values.transcrobes.zhEnCedict.inmem }}"
            - name: TRANSCROBES_ZH_EN_ABC_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhEnAbcDict.path }}"
            - name: TRANSCROBES_ZH_EN_ABC_DICT_INMEM
              value: "{{ .Values.transcrobes.zhEnAbcDict.inmem }}"
            - name: TRANSCROBES_ZH_HSK_LISTS_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhHskLists.path }}"
            - name: TRANSCROBES_ZH_HSK_LISTS_INMEM
              value: "{{ .Values.transcrobes.zhHskLists.inmem }}"
            - name: TRANSCROBES_BING_TRANSLATOR_INMEM
              value: "{{ .Values.transcrobes.bingTranslator.inmem }}"
            - name: TRANSCROBES_BING_TRANSLITERATOR_INMEM
              value: "{{ .Values.transcrobes.bingTransliterator.inmem }}"
            - name: TRANSCROBES_ZH_SUBTLEX_FREQ_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhSubtlexFreq.path }}"
            - name: TRANSCROBES_ZH_SUBTLEX_FREQ_INMEM
              value: "{{ .Values.transcrobes.zhSubtlexFreq.inmem }}"
            - name: TRANSCROBES_BROACASTER_MESSAGING_LAYER
              value: "{{ .Values.transcrobes.broadcasterMessagingLayer }}"
            - name: TRANSCROBES_KAFKA_BROKER
              value: "{{ .Values.kafka.fullnameOverride }}"
            - name: TRANSCROBES_KAFKA_CONSUMER_TIMEOUT_MS
              value: "{{ .Values.statsrunner.kafkaConnection.consumerTimeoutMs }}"
            - name: TRANSCROBES_KAFKA_STATS_LOOP_SLEEP_SECS
              value: "{{ .Values.statsrunner.kafkaConnection.statsLoopSleepSecs }}"
            - name: TRANSCROBES_KAFKA_MAX_POLL_RECORDS
              value: "{{ .Values.statsrunner.kafkaConnection.maxPollRecords }}"

      {{- if .Values.transcrobes.persistence.enabled }}
          volumeMounts:
          - mountPath: "{{ .Values.transcrobes.persistence.dataRoot }}"
            name: {{ include "transcrobes.transcrobes.fullname" . }}
      volumes:
        - name: {{ include "transcrobes.transcrobes.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "transcrobes.transcrobes.fullname" . }}
      {{- end }}

      restartPolicy: Always
status: {}
{{- end }}
