{{- if .Values.certissuer.staging.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certissuer.staging.name }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ required "A valid .Values.certissuer.staging.email entry required!" .Values.certissuer.staging.email }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ .Values.certissuer.staging.privateKeySecretRef }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
