{{- if .Values.transcrobes.enabled -}}
{{- $fullName := include "transcrobes.transcrobes.fullname" . -}}
{{- $ingressPath := .Values.transcrobes.authingress.path -}}
{{- $servicePort := .Values.transcrobes.service.servicePort -}}
{{- $reallyFullName := include "transcrobes.transcrobes.reallyFullname" . -}}
{{- $authUrl := printf "%s%s%s" "http://" $reallyFullName "/authget" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.nginxingress.controller.ingressClass }}
    nginx.ingress.kubernetes.io/auth-url: {{ $authUrl }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.transcrobes.authingress.tls.issuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.transcrobes.authingress.maxBodySize }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: withauth
  labels:
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}

spec:
{{- if .Values.transcrobes.authingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.transcrobes.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.transcrobes.authingress.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.transcrobes.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
