{{- if .Values.transcrobes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transcrobes.transcrobes.fullname" . }}
  labels:
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.transcrobes.replicaCount }}
  {{- if .Values.transcrobes.strategy }}
  strategy:
{{ toYaml .Values.transcrobes.strategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transcrobes.transcrobes.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.transcrobes.podAnnotations }}
      annotations:
{{ toYaml .Values.transcrobes.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "transcrobes.transcrobes.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:11
          command: ['sh', '-c',
            'until psql -c "select 1;";
            do echo waiting for database; sleep 2; done;']
          env:
            - name: PGUSER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: PGDATABASE
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: PGPASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: PGHOST
              value: "{{ .Values.postgresql.fullnameOverride }}"
      containers:
        - name: {{ template "transcrobes.name" . }}-{{ .Values.transcrobes.name }}
          image: "{{ .Values.transcrobes.image.repository }}:{{ .Values.transcrobes.image.tag }}"
          imagePullPolicy: {{ .Values.transcrobes.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.transcrobes.application.listenPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.transcrobes.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: PYTHONUNBUFFERED  # MUST put or no logs printed to kube, but probably should be in values
              value: "0"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: POSTGRES_DATABASE
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.postgresql.fullnameOverride }}"
            - name: TRANSCROBES_PUBLIC_HOSTS  # this is poorly named as it includes non-public hosts
              value: {{ include "transcrobes.publichosts" . }},{{ include "transcrobes.transcrobes.fullname" . }},{{ include "transcrobes.transcrobes.reallyFullname" . }}
            - name: TRANSCROBES_SECRET_KEY
              value: "{{ .Values.transcrobes.secretKey }}"
            - name: TRANSCROBES_GUNICORN_WORKERS
              value: "{{ .Values.transcrobes.application.gunicornWorkers }}"
            - name: TRANSCROBES_LISTEN_ADDRESS
              value: "{{ .Values.transcrobes.application.listenAddress }}"
            - name: TRANSCROBES_LISTEN_PORT
              value: "{{ .Values.transcrobes.application.listenPort }}"
            - name: TRANSCROBES_CORENLP_HOST_ZH
              value: {{ include "transcrobes.corenlpZh.fullname" . }}
            - name: TRANSCROBES_CORENLP_HOST_EN
              value: {{ include "transcrobes.corenlpEn.fullname" . }}
            {{- if .Values.transcrobes.debug }}
            - name: TRANSCROBES_DEBUG
              value: "True"
            {{- end }}
            - name: TRANSCROBES_BING_SUBSCRIPTION_KEY
              value: "{{ .Values.transcrobes.bingSubscriptionKey }}"
            - name: TRANSCROBES_BING_API_HOST
              value: "{{ .Values.transcrobes.bingApiHost }}"
            - name: TRANSCROBES_CC_CEDICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.ccCedict.path }}"
            - name: TRANSCROBES_CC_CEDICT_INMEM
              value: "{{ .Values.transcrobes.ccCedict.inmem }}"
            - name: TRANSCROBES_ABC_ZH_EN_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.abcZhEnDict.path }}"
            - name: TRANSCROBES_ABC_ZH_EN_DICT_INMEM
              value: "{{ .Values.transcrobes.abcZhEnDict.inmem }}"
            - name: TRANSCROBES_ABC_EN_ZH_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.abcEnZhDict.path }}"
            - name: TRANSCROBES_ABC_EN_ZH_DICT_INMEM
              value: "{{ .Values.transcrobes.abcEnZhDict.inmem }}"
            - name: TRANSCROBES_HSK_LISTS_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.hskLists.path }}"
            - name: TRANSCROBES_HSK_LISTS_INMEM
              value: "{{ .Values.transcrobes.hskLists.inmem }}"
            - name: TRANSCROBES_SUBTLEX_FREQ_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.subtlexFreq.path }}"
            - name: TRANSCROBES_SUBTLEX_FREQ_INMEM
              value: "{{ .Values.transcrobes.subtlexFreq.inmem }}"
            - name: TRANSCROBES_CMU_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.cmuDict.path }}"
            - name: TRANSCROBES_CMU_DICT_INMEM
              value: "{{ .Values.transcrobes.cmuDict.inmem }}"

      {{- if .Values.transcrobes.persistence.enabled }}
          volumeMounts:
          - mountPath: "{{ .Values.transcrobes.persistence.dataRoot }}"
            name: {{ include "transcrobes.transcrobes.fullname" . }}
      volumes:
        - name: {{ include "transcrobes.transcrobes.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "transcrobes.transcrobes.fullname" . }}
      {{- end }}

      restartPolicy: Always
status: {}
{{- end }}
